news/urls.py
from django.urls import path
from .views import *

app_name= 'news'

urlpatterns = [
    path('home/',home,name="home"),
    path('articoli/<int:pk>',articoloDetailView, name="articolo_detail"),
    path('giornalista/<int:pk>',giornalistaDetailView, name="giornalista_detail"),
    path('giornalista/lista/<int:pk>',listaArticoli, name="lista_articoli_giornalista"),
    path('giornalista/lista/',listaArticoli, name="lista_articoli"),
    path('lista/',query_base, name="query_base"),
    path('indexnews/',indexnews,name="indexnews"),
    path('giornalisti_list_api',giornalisti_list_api, name="giornalista_list_api"),
    path('giornalista_api/<int:pk>',giornalista_api,name="giornalista_api"),
    path('articoli_list_api',articoli_list_api,name="articoli_list_api"),
    path('articolo_api/<int:pk>',articolo_api,name="articolo_api")
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage,welcome,lista,chi_siamo,variabili,index

app_name="prima_app"
urlpatterns=[
    path('',index,name='index'),
    path('homepage',homepage,name='homepage'),
    path('welcome',welcome,name='welcome'),
    path('lista',lista,name='lista'),
    path('chi_siamo',chi_siamo,name='chi_siamo'),
    path('variabili',variabili,name='variabili'),  
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('',index,name='index'),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('prova_pratica_1/',include("prova_pratica_1.urls",namespace="prova_pratica_1")),
    path('news/',include("news.urls",namespace="news")),
    path('voti/',include("voti.urls",namespace="voti")),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
    # path('products/',include("products.urls",namespace="products")),

]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

prova_pratica_1/urls.py
from django.urls import path
from prova_pratica_1.views import index_prova,somma,media,voti

app_name="prova_pratica_1"
urlpatterns=[
    path('index_prova',index_prova,name='index_prova'),
    path('somma',somma,name='somma'),
    path('media',media,name='media'),
    path('voti',voti,name='voti'),

]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import es_if,if_else_elif,es_for,index2

app_name="seconda_app"
urlpatterns=[
    path('es_if',es_if,name='es_if'),
    path('if_else_elif',if_else_elif,name='if_else_elif'),
    path('es_for',es_for,name='es_for'),
    path('index2',index2,name='index2'),

]

voti/urls.py
from django.urls import path
from .views import homepage_voti,viewA,viewB

app_name='voti'

urlpatterns = [
    path('',homepage_voti,name='homepage_voti'),
    path('viewA/', viewA, name='viewA'),
    path('viewB/', viewB, name='viewB'),
    #path('viewD/', viewD, name=viewD),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head><!-- sezione head compressa al suo interno i link per caricare le risorse del template-->
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{%block title%} Primo progetto {%endblock title%}</title>
  </head>
  <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="/">primo progetto</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

              {% if request.user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'index' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ request.user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}"> Esci </a>
                </div>
              </li>
              {% else %}
                {% comment %} <li class="nav-item">
                  <a class="nav-link" href="{% url 'forms_app:registration_view' %}">Registrati </a>
                </li> {% endcomment %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}

              



              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'index' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  prima app
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">homepage</a>
                  <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">welcome</a>
                  <a class="dropdown-item" href="{% url 'prima_app:lista'%}">lista</a>
                  <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%}">chi_siamo</a>
                  <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">variabili</a>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  seconda app
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'seconda_app:index2'%}">homepage</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">es_if</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">if else if</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">es_for</a>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   prova pratica
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'prova_pratica_1:index_prova'%}">homepage</a>
                  <a class="dropdown-item" href="{% url 'prova_pratica_1:somma'%}">somma</a>
                  <a class="dropdown-item" href="{% url 'prova_pratica_1:media'%}">media</a>
                  <a class="dropdown-item" href="{% url 'prova_pratica_1:voti'%}">voti</a>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    voti
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'voti:homepage_voti'%}">homepage</a>
                  <a class="dropdown-item" href="{% url 'voti:viewA' %}">somma</a>
                  <a class="dropdown-item" href="{% url 'voti:viewB' %}">media</a>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    News
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'news:indexnews'%}">indexnews</a>
                  <a class="dropdown-item" href="{% url 'news:home'%}">homepage</a>
                  <a class="dropdown-item" href="{% url 'news:query_base' %}">query</a>
                  <a class="dropdown-item" href="{% url 'news:lista_articoli' %}">lista</a>
                </div>
              </li>



            </ul>
          </div>
        </nav>

        
      <div class="container my-4">
        <!-- servirà per inserire i contenuti della pagina -->
        {%block content%}
        {%endblock content%}
        <!-- servirà per inserire il codice javascript-->
        {%block script%}
        {%endblock script%}

        
      </div>

  
    </body>
</html>

templates/index_root.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block title%} {{block.super}} | index_root {%endblock title%}
</head>
<body>
    {%block content%}
    <ol>
        <li><a href="/admin">pannello admin</a></li>
        <li><a href="{% url 'prima_app:index'%}">prima app</a></li>
        <li><a href="{% url 'seconda_app:index2'%}">seconda app</a></li>
        <li><a href="{% url 'prova_pratica_1:index_prova'%}">prova pratica</a></li>
        <li><a href="{% url 'voti:homepage_voti'%}">voti</a></li>
        <li><a href="{% url 'news:indexnews'%}">news</a></li>
    </ol>
    {%endblock content%}
    
</body>
</html>