news/urls.py
from django.urls import path
from .views import *

app_name= 'news'

urlpatterns = [
    path('home/',home,name="home"),
    path('articoli/<int:pk>',articoloDetailView, name="articolo_detail"),
    path('giornalista/<int:pk>',giornalistaDetailView, name="giornalista_detail"),
    path('giornalista/lista/<int:pk>',listaArticoli, name="lista_articoli_giornalista"),
    path('giornalista/lista/',listaArticoli, name="lista_articoli"),
    path('lista/',query_base, name="query_base"),
    path('indexnews/',indexnews,name="indexnews"),
    path('giornalisti_list_api',giornalisti_list_api, name="giornalista_list_api"),
    path('giornalista_api/<int:pk>',giornalista_api,name="giornalista_api"),
    path('articoli_list_api',articoli_list_api,name="articoli_list_api"),
    path('articolo_api/<int:pk>',articolo_api,name="articolo_api")
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('',index,name='index'),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('prova_pratica_1/',include("prova_pratica_1.urls",namespace="prova_pratica_1")),
    path('news/',include("news.urls",namespace="news")),
    path('voti/',include("voti.urls",namespace="voti")),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
    # path('products/',include("products.urls",namespace="products")),

]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

news/models.py
from django.db import models
# Create your models here.

class Giornalista(models.Model):
    "modello generico di un giornalista"
    nome=models.CharField(max_length=20)
    cognome=models.CharField(max_length=20)
    anno_di_nascita=models.DateField(blank=True)

    def __str__(self):
        return self.nome + " " + self.cognome

    class Meta:
        verbose_name = "Giornalista"
        verbose_name_plural = "Giornalisti"
    
class Articolo(models.Model):
    "modello generico di un articolo"
    titolo=models.CharField(max_length=100)
    contenuto=models.TextField()
    giornalista=models.ForeignKey(Giornalista,on_delete=models.CASCADE,related_name="articoli")
    visualizzazioni=models.CharField(max_length=1000)
    data=models.DateField(blank=True)


    def __str__(self):
        return self.titolo

    class Meta:
        verbose_name = "Articolo"
        verbose_name_plural = "Articoli"

news/views.py
from django.http import JsonResponse
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import *
import datetime
# Create your views here.

"""
def home(request):
    a=""
    g=""
    for art in Articolo.objects.all():
        a+=(art.titolo+ "<br>")

    for gio in Giornalista.objects.all():
        g+=(gio.nome + "<br>")
    response="Articoli:<br>" + a + "<br>Giornalisti:<br>" +g
    
    return HttpResponse("<h1>" +response+"</h1>")    


def home(request):
    a=[]
    g=[]
    for art in Articolo.objects.all():
        a.append(art.titolo)

    for gio in Giornalista.objects.all():
        g.append(gio.nome)

    response=str(a) +"<br>" +str(g)
    print(response)
    return HttpResponse("<h1>" +response+"</h1>")
"""
def home(request):
    articoli=Articolo.objects.all()
    giornalisti=Giornalista.objects.all()
    context={"articoli": articoli, "giornalisti": giornalisti}
    print(context)
    return render(request, "homepage_news.html",context)


def articoloDetailView(request,pk):
    articolo = get_object_or_404(Articolo, pk=pk)
    context  = {"articolo": articolo}
    return render(request, "articolo_detail.html",context)


def giornalistaDetailView(request,pk):
    giornalista = get_object_or_404(Giornalista, pk=pk)
    articoli = Articolo.objects.filter(giornalista_id=pk)
    context = {'giornalista': giornalista,
               'articoli':articoli,
               }
    return render(request, "giornalista_detail.html",context)


def listaArticoli(request,pk=None):
    if(pk==None):
        articoli=Articolo.objects.all()
    else:
        articoli = Articolo.objects.filter(giornalista_id=pk)
    context ={
        'articoli':articoli,
    }
    return render(request, "lista_articoli.html",context)

def indexnews(request):
    return render(request, "indexnews.html")

"""
nella prima versione le variabili a e g erano stringe le quali ad a tramite un ciclo 
venivano assegnati tutti i titoli degli articoli mentre a g tutti i nomi dei giornalisti
infine a e g venivano contecatenate in una variabile responde che che verra 
poi restituita con httpresponse() nella seconda versione a e g sono invece
due array nei quali vengono aggiungi nel primo i titoli degli articoli e nel
secondo i nomi dei giornalisti poi usando il metodo str aggiunto nelle classi 
nel models.py mettiamo nella variabile response a e g e restituiamo gli array con 
httpresponse()

"""

def query_base(request):
    pass
    #1. tutti gli articoli scritti da giornalisti con un certo cognome
    articoli_cognome=Articolo.objects.filter(giornalista__cognome='Rossi')
    
    #2. Totale
    numero_totale_articoli = Articolo.objects.count()

    #3. Contare il numero di articoli scritti da un giornalista specifico
    giornalista_1 = Giornalista.objects.get(id=3)
    numero_articoli_giornalista_1=Articolo.objects.filter(giornalista=giornalista_1).count()

    #4. Ordinare gli articoli per numero di articoli in ordine decrescente
    articoli_ordinati = Articolo.objects.order_by('-visualizzazioni')

    #5. tutti gli articoli che non hanno visualizzazioni:
    articoli_senza_visualizzazioni = Articolo.objects.filter(visualizzazioni=0)

    #6. articolo più visualizzato 
    articolo_piu_visualizzato = Articolo.objects.order_by('-visualizzazioni').first()

    #7. tutti i giornalisti nati dopo una certa data
    giornalisti_data=Giornalista.objects.filter(anno_di_nascita__gt=datetime.date(1990, 1, 1))

    #8. tutti gli articoli pubblicati in una data specifica
    articoli_del_giorno=Articolo.objects.filter(data=datetime.date(2023,1,1))

    #9. tutti gli articoli pubblicati in un intervallo di date
    articoli_periodo= Articolo.objects.filter(data__range=(datetime.date(2023, 1, 1), datetime.date(2023,12,31)))

    #10. gli articoli scritti da giornalisti prima del 1980
    giornalisti_nati = Giornalista.objects.filter(anno_di_nascita__lt=datetime.date(1980, 1, 1))
    articoli_giornalisti = Articolo.objects.filter(giornalista__in=giornalisti_nati)

    #11. il giornalista più giovane
    giornalista_giovane = Giornalista.objects.order_by('anno_di_nascita').first()

    #12. il giornalista più anziano
    giornalista_anziano = Giornalista.objects.order_by('-anno_di_nascita').first()

    #13. gli ultimi 5 articoli pubblicati
    ultimi = Articolo.objects.order_by('-data')[:5]

    #14. tutti gli articoli con un certo numero minimo di visualizzazioni
    articoli_minime_visualizzazioni = Articolo.objects.filter(visualizzazioni__gte=100)

    #15. tutti gli articoli che contengono una certa parola nel titolo
    articoli_parola = Articolo.objects.filter(titolo__icontains='importante')
    #16. articoli pubblicati in un certo mese di anno specifico
    #nota per poter modificare la data di un articolo togliere la proprietà auto_now=true al field data nel model
    #poi dare i comandi makemigration e migrate per abblicare le modifiche al database
    articoli_mese_anno=Articolo.objects.filter(data__month=1, data__year=2023)
    #17. giornalisti con almeno un articolo con più di 100 visualizzazioni
    giornalisti_con_articoli_popolari= Giornalista.objects.filter(articoli__visualizzazioni__gte=100).distinct()
    #UTILIZZO DI PIU CONDIZIONI DI SELEZIONE
    data=datetime.date(1990,1,1)
    visualizzazioni=50
    #per mettere in AND le condizioni separarle con la virgola
    #18 ...scrivi quali articoli vengono selezionati
    articoli_con_and=Articolo.objects.filter(giornalista__anno_di_nascita__gt=data, visualizzazioni__gte=visualizzazioni)

    #per mettere le condizioni in OR utilizzare l'operatore Q
    from django.db.models import Q
    #19. scrivi quali articoli vengono selezionati
    articoli_con_or=Articolo.objects.filter(Q(giornalista__anno_di_nascita__gt=data) |Q(visualizzazioni__lte=visualizzazioni))
    
    #per il not utilizzare l'operatore Q
    #20 ... scrivi quali articoli vengono selezionati
    #creare il dizionario context
    articoli_con_not= Articolo.objects.filter(~Q(giornalista__anno_di_nascita__lt=data))
    #oppure il metodo exclude
    # ... spiegala
    articoli_con_not = Articolo.objects.exclude(giornalista__anno_di_nascita__lt=data)
    #articolo.objects inizia dalla classe articolo exclude ritorna tutti i giornalisti tranne quelli la cui condizione risulta vera

    context = {
        'articolo_cognome': articoli_cognome,
        'numero_totale_articoli':numero_totale_articoli,
        'giornalista_1':giornalista_1,
        'numero_articoli_giornalista_1':numero_articoli_giornalista_1,
        'articoli_ordinati':articoli_ordinati,
        'articoli_senza_visualizzazioni':articoli_senza_visualizzazioni,
        'articolo_piu_visualizzato':articolo_piu_visualizzato,
        'giornalisti_data':giornalisti_data,
        'articoli_del_giorno':articoli_del_giorno,
        'articoli_periodo':articoli_periodo,
        'giornalisti_nati':giornalisti_nati,
        'articoli_giornalisti':articoli_giornalisti,
        'giornalista_giovane':giornalista_giovane,
        'giornalista_anziano':giornalista_anziano,
        'ultimi':ultimi,
        'articoli_minime_visualizzazioni':articoli_minime_visualizzazioni,
        'articoli_parola':articoli_parola,
        'articoli_mese_anno':articoli_mese_anno,
        'giornalisti_con_articoli_popolari':giornalisti_con_articoli_popolari,
        'articoli_con_and':articoli_con_and,
        'articoli_con_or':articoli_con_or,
        'articoli_con_not':articoli_con_not,
    }
    return render(request, 'query.html',context)

def giornalisti_list_api(request):
    giornalisti=Giornalista.objects.all()
    data={'giornalisti':list(giornalisti.values("pk","nome","cognome"))}
    response=JsonResponse(data)
    return response

def giornalista_api(request,pk):
    try:
        giornalista=Giornalista.objects.get(pk=pk)
        data={'giornalista':{
            "nome":giornalista.nome,
            "cognome":giornalista.cognome,
        }
        }
        response=JsonResponse(data)
    except Giornalista.DoesNotExist:
        response=JsonResponse({
            "error":{
                "code":404,
                "message":"giornalista non trovato"
            }
        },
        status=404)
    return response

def articoli_list_api(request):
    articolo=Articolo.objects.all()
    data={'articoli':list(articolo.values("titolo","contenuto","giornalista","visualizzazioni","data"))}
    response=JsonResponse(data)
    return response

def articolo_api(request,pk):
    try:
        articolo=Articolo.objects.get(pk=pk)
        data={'articoli':{"titolo":articolo.titolo,
                      "contenuto":articolo.contenuto,
                      "giornalista":articolo.giornalista.nome,
                      "visualizzazioni":articolo.visualizzazioni,
                      "data":articolo.data}}
        response=JsonResponse(data)
    except Articolo.DoesNotExist:
        response=JsonResponse({"error":{'code':404,'message':'articolo non trovato'}},
                              status=404)
    return response



                        

news/templates/articolo_detail.html
{%extends "base.html"%}

{%block title%} {{block.super}} | {{ articolo.titolo }} {%endblock title%}

{% block content %}

<h1>{{ articolo.titolo }}</h1>
<h3>{{ articolo.contenuto }}</h3>
<h5>Autore: {{ articolo.giornalista }}</h5>
{%endblock content%}

news/templates/giornalista_detail.html
{%extends "base.html"%}

{%block title%} {{block.super}} | {{ articolo.titolo }} {%endblock title%}

{% block content %}

<h1>dettagli del giornalista:</h1>
<h1>{{ giornalista.nome }} {{ giornalista.cognome }} </h1>
<h3>anno di nascita: {{ giornalista.anno_di_nascita }}</h3>
<h3>tutti i suoi articoli e pubblicazioni </h3>
<ul>
{% for articolo in articoli %}
<li><a href="{% url 'news:articolo_detail' articolo.id %}"> {{ articolo.titolo }} </a></li>
{% endfor %}
</ul>
{%endblock content%}

news/templates/homepage_news.html
{%extends "base.html"%}

{%block title%} {{block.super}} | Homepage {%endblock title%}

{% block content %}
<h4>Articoli: </h4>
{% for articolo in articoli %}
    <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
    <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
    <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
    <hr>
{% endfor %}
<h4>Giornalisti</h4>
{% for giornalista in giornalisti %}
<p><strong>Nome: </strong>{{ articolo.nome }}</p>
<p><strong>Cognome: </strong>{{ articolo.cognome }}</p>
<hr>
{% endfor %}
{%endblock content%}

news/templates/indexnews.html
{%extends "base.html"%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block title%} {{block.super}} | index {%endblock title%}
</head>
<body>
    {%block content%}
    <ol>
        <li><a href="{% url 'news:home'%}">Homepage </a></li>
        <li><a href="{% url 'news:lista_articoli'%}">lista articoli</a></li>
        <li><a href="{% url 'news:query_base'%}">query</a></li>
        <li><a href="{% url 'news:giornalista_list_api' %}">lista giornalisti API</a></li>
        <li><a href="{% url 'news:articoli_list_api' %}">lista articoli API</a></li>
    </ol>
    {%endblock content%}
    
</body>
</html>

news/templates/lista_articoli.html
{%extends "base.html"%}

{%block title%} {{block.super}} | Articoli di un giornalista {%endblock title%}

{% block content %}

{% for articolo in articoli%}
<p><strong> Titolo: </strong> 
  {% comment %} metodo non ottimale per creare il link 
  <a href="news/articoli/{{ articoli.id }}">{{ articolo.titolo }}</a>
  {% endcomment %}
  <a href={% url 'news:articolo_detail' articolo.id %}>{{ articolo.titolo }}</a>
</p>

<p><strong>contenuto: </strong>
articolo.contenuto
</p>

{% comment %} metodo ottimale per creare il link {% endcomment %}
<p><strong>Autore:</strong>
<a href={% url 'news:giornalista_detail' articolo.giornalista.id %}>{{ articolo.giornalista }}</a>
</p>
<hr>

{%endfor%}


{%endblock content%}

news/templates/query.html
{%extends "base.html"%}

{%block title%} {{block.super}} | Query {%endblock title%}

{% block content %}
<h5>articoli di un certo giornalista</h5>
{% for articolo in articoli_cognome %}
<div>
    {% comment %} <p>{{ articolo.titolo }}</p> {% endcomment %}
    <p>{{ articolo.contenuto }}</p>
    <p>{{ articolo.giornalista }}</p>
    <p>{{ articolo.visualizzazioni }}</p>
    <p>{{ articolo.data }}</p>
</div>
{%endfor%}

<h5>numero totale di articoli</h5>
<div>
<p>{{ numero_totale_articoli }}</p>
</div>

<h5>numero di articoli scritti da un giornalista specifico</h5>
<div>
<p>{{ numero_articoli_giornalista_1 }} </p>
</div>

<h5>articoli ordinati visualizzazioni decrescenti</h5>
<div>
{%for articolo in articoli_ordinati %}
    <p>{{ articolo.titolo }}</p>
    <p>{{ articolo.contenuto }}</p>
    <p>{{ articolo.giornalista }}</p>
    <p>{{ articolo.visualizzazioni }}</p>
    <p>{{ articolo.data }}</p>
{%endfor%}
</div>

<h5>articoli senza visualizzazioni</h5>
<div>
{%for articolo in articoli_senza_visualizzazioni %}
    <p>{{ articolo.titolo }}</p>
    <p>{{ articolo.contenuto }}</p>
    <p>{{ articolo.giornalista }}</p>
    <p>{{ articolo.visualizzazioni }}</p>
    <p>{{ articolo.data }}</p>
{%endfor%}
</div>

<h5>articolo più visualizzato</h5>
<div>
    <p>{{ articolo_piu_visualizzato.titolo }}</p>
    <p>{{ articolo_piu_visualizzato.contenuto }}</p>
    <p>{{ articolo_piu_visualizzato.giornalista }}</p>
    <p>{{ articolo_piu_visualizzato.visualizzazioni }}</p>
    <p>{{ articolo_piu_visualizzato.data }}</p>
</div>

<h5>giornalisti nati dopo una certa data</h5>
<div>
{%for giornalista in giornalisti_data %}
    <p>{{ giornalista.nome }}</p>
    <p>{{ giornalista.cognome }}</p>
    <p>{{ giornalista.anno_di_nascita }}</p>
{%endfor%}
</div>

<h5>articoli pubblicati in una data specifica</h5>
<div>
{%for articolo in articoli_del_giorno %}
    <p>{{ articolo.titolo }}</p>
    <p>{{ articolo.contenuto }}</p>
    <p>{{ articolo.giornalista }}</p>
    <p>{{ articolo.visualizzazioni }}</p>
    <p>{{ articolo.data }}</p>
{%endfor%}
</div>

<h5>articoli pubblicato in un intervallo di date </h5>
<div>
{%for articolo in articoli_periodo %}
    <p>{{ articolo.titolo }}</p>
    <p>{{ articolo.contenuto }}</p>
    <p>{{ articolo.giornalista }}</p>
    <p>{{ articolo.visualizzazioni }}</p>
    <p>{{ articolo.data }}</p>
{%endfor%}
</div>

<h5>articoli scritti da giornalisti prima degli anni 80</h5>
<div>
{%for articolo in articoli_giornalista %}
    <p>{{ articolo.titolo }}</p>
    <p>{{ articolo.contenuto }}</p>
    <p>{{ articolo.giornalista }}</p>
    <p>{{ articolo.visualizzazioni }}</p>
    <p>{{ articolo.data }}</p>
{%endfor%}
</div>

<h5>giornalista più giovane</h5>
<div>
    <p>{{ giornalista_giovane.nome }}</p>
    <p>{{ giornalista_giovane.cognome }}</p>
    <p>{{ giornalista_giovane.anno_di_nascita }}</p>
</div>

<h5>giornalista più anziano</h5>
<div>
    <p>{{ giornalista_anziano.nome }}</p>
    <p>{{ giornalista_anziano.cognome }}</p>
    <p>{{ giornalista_anziano.anno_di_nascita }}</p>
</div>

<h5>ultimi 5 articoli pubblicati</h5>
<div>
{%for articolo in ultimi %}
    <p>{{ articolo.titolo }}</p>
    <p>{{ articolo.contenuto }}</p>
    <p>{{ articolo.giornalista }}</p>
    <p>{{ articolo.visualizzazioni }}</p>
    <p>{{ articolo.data }}</p>
{%endfor%}
</div>

<h5>tutti gli articoli con un certo numero di visualizzazioni</h5>
<div>
    {%for articolo in articoli_minime_visualizzazioni %}
        <p>{{ articolo.titolo }}</p>
        <p>{{ articolo.contenuto }}</p>
        <p>{{ articolo.giornalista }}</p>
        <p>{{ articolo.visualizzazioni }}</p>
        <p>{{ articolo.data }}</p>
    {%endfor%}
</div>

<h5>tutti gli articoli che contengono la parola "importante nel titolo"</h5>
<div>
    {%for articolo in articoli_parola %}
        <p>{{ articolo.titolo }}</p>
        <p>{{ articolo.contenuto }}</p>
        <p>{{ articolo.giornalista }}</p>
        <p>{{ articolo.visualizzazioni }}</p>
        <p>{{ articolo.data }}</p>
    {%endfor%}
</div>

<h5>articoli pubblicati in un certo mese di un anno specifico</h5>
<div>
    {%for articolo in articoli_mese_anno %}
        <p>{{ articolo.titolo }}</p>
        <p>{{ articolo.contenuto }}</p>
        <p>{{ articolo.giornalista }}</p>
        <p>{{ articolo.visualizzazioni }}</p>
        <p>{{ articolo.data }}</p>
    {%endfor%}
</div>

<h5>giornalisti con almeno 1 articolo con più di 100 visualizzazioni</h5>
<div>
    {%for giornalista in giornalisti_con_articoli_popolari %}
        <p>{{ giornalista.nome }}</p>
        <p>{{ giornalista.cognome }}</p>
        <p>{{ giornalista.anno_di_nascita }}</p>
    {%endfor%}
</div>

<h5>articoli selezionati con AND</h5>
<div>
    {%for articolo in articoli_con_and %}
        <p>{{ articolo.titolo }}</p>
        <p>{{ articolo.contenuto }}</p>
        <p>{{ articolo.giornalista }}</p>
        <p>{{ articolo.visualizzazioni }}</p>
        <p>{{ articolo.data }}</p>
    {%endfor%}
</div>

<h5>articoli selezionati con OR</h5>
<div>
    {%for articolo in articoli_con_or %}
        <p>{{ articolo.titolo }}</p>
        <p>{{ articolo.contenuto }}</p>
        <p>{{ articolo.giornalista }}</p>
        <p>{{ articolo.visualizzazioni }}</p>
        <p>{{ articolo.data }}</p>
    {%endfor%}
</div>

<h5>articoli selezionati con NOT</h5>
    <div>
        {%for articolo in articoli_con_not %}
            <p>{{ articolo.titolo }}</p>
            <p>{{ articolo.contenuto }}</p>
            <p>{{ articolo.giornalista }}</p>
            <p>{{ articolo.visualizzazioni }}</p>
            <p>{{ articolo.data }}</p>
        {%endfor%}
    </div>




{%endblock content%}